name: Docker Image CI (nightly)

on:
  push:
    branches:
      - dev

jobs:
  build-nightly:
    uses: ./.github/workflows/docker-image.yml
    with:
      image_name: ${{ github.repository_owner }}/godoxy-frontend
      tag: nightly
